
package com.store.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServicePortType", targetNamespace = "http://store.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.store.soap.client.GetProductResponse
     */
    @WebMethod(action = "http://store.com/getProduct")
    @WebResult(name = "getProductResponse", targetNamespace = "http://store.com/", partName = "parameters")
    public GetProductResponse getProduct(
        @WebParam(name = "getProductRequest", targetNamespace = "http://store.com/", partName = "parameters")
        GetProductRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.store.soap.client.UpdateProductResponse
     */
    @WebMethod(action = "http://store.com/updateProduct")
    @WebResult(name = "updateProductResponse", targetNamespace = "http://store.com/", partName = "parameters")
    public UpdateProductResponse updateProduct(
        @WebParam(name = "updateProductRequest", targetNamespace = "http://store.com/", partName = "parameters")
        UpdateProductRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.store.soap.client.DeleteProductResponse
     */
    @WebMethod(action = "http://store.com/deleteProduct")
    @WebResult(name = "deleteProductResponse", targetNamespace = "http://store.com/", partName = "parameters")
    public DeleteProductResponse deleteProduct(
        @WebParam(name = "deleteProductRequest", targetNamespace = "http://store.com/", partName = "parameters")
        DeleteProductRequest parameters);

}
