
package com.store.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductService", targetNamespace = "http://store.com/", wsdlLocation = "file:/Users/samy/Desktop/Projects/specmatic-order-api-soap/src/main/resources/api_order_v3.wsdl")
public class ProductService
    extends Service
{

    private final static URL PRODUCTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSERVICE_EXCEPTION;
    private final static QName PRODUCTSERVICE_QNAME = new QName("http://store.com/", "ProductService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/samy/Desktop/Projects/specmatic-order-api-soap/src/main/resources/api_order_v3.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSERVICE_WSDL_LOCATION = url;
        PRODUCTSERVICE_EXCEPTION = e;
    }

    public ProductService() {
        super(__getWsdlLocation(), PRODUCTSERVICE_QNAME);
    }

    public ProductService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSERVICE_QNAME, features);
    }

    public ProductService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSERVICE_QNAME);
    }

    public ProductService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSERVICE_QNAME, features);
    }

    public ProductService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "ProductServicePort")
    public ProductServicePortType getProductServicePort() {
        return super.getPort(new QName("http://store.com/", "ProductServicePort"), ProductServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "ProductServicePort")
    public ProductServicePortType getProductServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://store.com/", "ProductServicePort"), ProductServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "ProductServicePortImage")
    public ProductServicePortType getProductServicePortImage() {
        return super.getPort(new QName("http://store.com/", "ProductServicePortImage"), ProductServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "ProductServicePortImage")
    public ProductServicePortType getProductServicePortImage(WebServiceFeature... features) {
        return super.getPort(new QName("http://store.com/", "ProductServicePortImage"), ProductServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "OrderServicePort")
    public ProductServicePortType getOrderServicePort() {
        return super.getPort(new QName("http://store.com/", "OrderServicePort"), ProductServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "OrderServicePort")
    public ProductServicePortType getOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://store.com/", "OrderServicePort"), ProductServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "OrderServicePortId")
    public ProductServicePortType getOrderServicePortId() {
        return super.getPort(new QName("http://store.com/", "OrderServicePortId"), ProductServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductServicePortType
     */
    @WebEndpoint(name = "OrderServicePortId")
    public ProductServicePortType getOrderServicePortId(WebServiceFeature... features) {
        return super.getPort(new QName("http://store.com/", "OrderServicePortId"), ProductServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSERVICE_EXCEPTION!= null) {
            throw PRODUCTSERVICE_EXCEPTION;
        }
        return PRODUCTSERVICE_WSDL_LOCATION;
    }

}
